## 1 数据处理

In [1]:
# 下载数据
!wget -P /root/jupyter_notebook http://datasrc.tipdm.net:81/python/case/RectalCancer/clinical_data.csv
!wget -P /root/jupyter_notebook http://datasrc.tipdm.net:81/python/case/RectalCancer/Features.py
!wget -P /root/jupyter_notebook http://datasrc.tipdm.net:81/python/case/RectalCancer/dataset.zip
!unzip -d /root/jupyter_notebook dataset.zip

--2022-03-30 14:59:25--  http://datasrc.tipdm.net:81/python/case/RectalCancer/clinical_data.csv
正在解析主机 datasrc.tipdm.net... 203.88.218.216
正在连接 datasrc.tipdm.net|203.88.218.216|:81... 已连接。
已发出 HTTP 请求，正在等待回应... 200 OK
长度：1522 (1.5K) [text/csv]
正在保存至: “/root/jupyter_notebook/clinical_data.csv”

100%[======================================>] 1,522       --.-K/s   in 0s      

2022-03-30 14:59:26 (208 MB/s) - 已保存 “/root/jupyter_notebook/clinical_data.csv” [1522/1522])

--2022-03-30 14:59:26--  http://datasrc.tipdm.net:81/python/case/RectalCancer/Features.py
正在解析主机 datasrc.tipdm.net... 203.88.218.216
正在连接 datasrc.tipdm.net|203.88.218.216|:81... 已连接。
已发出 HTTP 请求，正在等待回应... 200 OK
长度：16885 (16K)
正在保存至: “/root/jupyter_notebook/Features.py”

100%[======================================>] 16,885      --.-K/s   in 0s      

2022-03-30 14:59:26 (142 MB/s) - 已保存 “/root/jupyter_notebook/Features.py” [16885/16885])

--2022-03-30 14:59:27--  http://datasrc.tipdm.net:81/python/case/RectalCancer/dataset.z

  inflating: /root/jupyter_notebook/dataset/1002/arterial phase/10008.dcm  
  inflating: /root/jupyter_notebook/dataset/1002/arterial phase/10008_mask.png  
  inflating: /root/jupyter_notebook/dataset/1002/arterial phase/10009.dcm  
  inflating: /root/jupyter_notebook/dataset/1002/arterial phase/10009_mask.png  
  inflating: /root/jupyter_notebook/dataset/1002/arterial phase/10010.dcm  
  inflating: /root/jupyter_notebook/dataset/1002/arterial phase/10010_mask.png  
  inflating: /root/jupyter_notebook/dataset/1002/arterial phase/10011.dcm  
  inflating: /root/jupyter_notebook/dataset/1002/arterial phase/10011_mask.png  
  inflating: /root/jupyter_notebook/dataset/1002/arterial phase/10012.dcm  
  inflating: /root/jupyter_notebook/dataset/1002/arterial phase/10012_mask.png  
  inflating: /root/jupyter_notebook/dataset/1002/arterial phase/10013.dcm  
  inflating: /root/jupyter_notebook/dataset/1002/arterial phase/10013_mask.png  
  inflating: /root/jupyter_notebook/dataset/1002/arterial 

  inflating: /root/jupyter_notebook/dataset/1004/arterial phase/10002.dcm  
  inflating: /root/jupyter_notebook/dataset/1004/arterial phase/10002_mask.png  
  inflating: /root/jupyter_notebook/dataset/1004/arterial phase/10003.dcm  
  inflating: /root/jupyter_notebook/dataset/1004/arterial phase/10003_mask.png  
  inflating: /root/jupyter_notebook/dataset/1004/arterial phase/10004.dcm  
  inflating: /root/jupyter_notebook/dataset/1004/arterial phase/10004_mask.png  
  inflating: /root/jupyter_notebook/dataset/1004/arterial phase/10005.dcm  
  inflating: /root/jupyter_notebook/dataset/1004/arterial phase/10005_mask.png  
  inflating: /root/jupyter_notebook/dataset/1004/arterial phase/10006.dcm  
  inflating: /root/jupyter_notebook/dataset/1004/arterial phase/10006_mask.png  
  inflating: /root/jupyter_notebook/dataset/1004/arterial phase/10007.dcm  
  inflating: /root/jupyter_notebook/dataset/1004/arterial phase/10007_mask.png  
  inflating: /root/jupyter_notebook/dataset/1004/arterial 

  inflating: /root/jupyter_notebook/dataset/1005/arterial phase/10001.dcm  
  inflating: /root/jupyter_notebook/dataset/1005/arterial phase/10001_mask.png  
  inflating: /root/jupyter_notebook/dataset/1005/arterial phase/10002.dcm  
  inflating: /root/jupyter_notebook/dataset/1005/arterial phase/10002_mask.png  
  inflating: /root/jupyter_notebook/dataset/1005/arterial phase/10003.dcm  
  inflating: /root/jupyter_notebook/dataset/1005/arterial phase/10003_mask.png  
  inflating: /root/jupyter_notebook/dataset/1005/arterial phase/10004.dcm  
  inflating: /root/jupyter_notebook/dataset/1005/arterial phase/10004_mask.png  
  inflating: /root/jupyter_notebook/dataset/1005/arterial phase/10005.dcm  
  inflating: /root/jupyter_notebook/dataset/1005/arterial phase/10005_mask.png  
  inflating: /root/jupyter_notebook/dataset/1005/arterial phase/10006.dcm  
  inflating: /root/jupyter_notebook/dataset/1005/arterial phase/10006_mask.png  
  inflating: /root/jupyter_notebook/dataset/1005/arterial 

  inflating: /root/jupyter_notebook/dataset/1006/arterial phase/10006.dcm  
  inflating: /root/jupyter_notebook/dataset/1006/arterial phase/10006_mask.png  
  inflating: /root/jupyter_notebook/dataset/1006/arterial phase/10007.dcm  
  inflating: /root/jupyter_notebook/dataset/1006/arterial phase/10007_mask.png  
  inflating: /root/jupyter_notebook/dataset/1006/arterial phase/10008.dcm  
  inflating: /root/jupyter_notebook/dataset/1006/arterial phase/10008_mask.png  
  inflating: /root/jupyter_notebook/dataset/1006/arterial phase/10009.dcm  
  inflating: /root/jupyter_notebook/dataset/1006/arterial phase/10009_mask.png  
  inflating: /root/jupyter_notebook/dataset/1006/arterial phase/10010.dcm  
  inflating: /root/jupyter_notebook/dataset/1006/arterial phase/10010_mask.png  
  inflating: /root/jupyter_notebook/dataset/1006/arterial phase/10011.dcm  
  inflating: /root/jupyter_notebook/dataset/1006/arterial phase/10011_mask.png  
  inflating: /root/jupyter_notebook/dataset/1006/arterial 

  inflating: /root/jupyter_notebook/dataset/1007/arterial phase/10002.dcm  
  inflating: /root/jupyter_notebook/dataset/1007/arterial phase/10002_mask.png  
  inflating: /root/jupyter_notebook/dataset/1007/arterial phase/10003.dcm  
  inflating: /root/jupyter_notebook/dataset/1007/arterial phase/10003_mask.png  
  inflating: /root/jupyter_notebook/dataset/1007/arterial phase/10004.dcm  
  inflating: /root/jupyter_notebook/dataset/1007/arterial phase/10004_mask.png  
  inflating: /root/jupyter_notebook/dataset/1007/arterial phase/10005.dcm  
  inflating: /root/jupyter_notebook/dataset/1007/arterial phase/10005_mask.png  
  inflating: /root/jupyter_notebook/dataset/1007/arterial phase/10006.dcm  
  inflating: /root/jupyter_notebook/dataset/1007/arterial phase/10006_mask.png  
  inflating: /root/jupyter_notebook/dataset/1007/arterial phase/10007.dcm  
  inflating: /root/jupyter_notebook/dataset/1007/arterial phase/10007_mask.png  
  inflating: /root/jupyter_notebook/dataset/1007/arterial 

  inflating: /root/jupyter_notebook/dataset/1007/venous phase/20016.dcm  
  inflating: /root/jupyter_notebook/dataset/1007/venous phase/20016_mask.png  
  inflating: /root/jupyter_notebook/dataset/1007/venous phase/20017.dcm  
  inflating: /root/jupyter_notebook/dataset/1007/venous phase/20017_mask.png  
  inflating: /root/jupyter_notebook/dataset/1007/venous phase/20018.dcm  
  inflating: /root/jupyter_notebook/dataset/1007/venous phase/20018_mask.png  
  inflating: /root/jupyter_notebook/dataset/1007/venous phase/20019.dcm  
  inflating: /root/jupyter_notebook/dataset/1007/venous phase/20019_mask.png  
  inflating: /root/jupyter_notebook/dataset/1007/venous phase/20020.dcm  
  inflating: /root/jupyter_notebook/dataset/1007/venous phase/20020_mask.png  
  inflating: /root/jupyter_notebook/dataset/1007/venous phase/20021.dcm  
  inflating: /root/jupyter_notebook/dataset/1007/venous phase/20021_mask.png  
  inflating: /root/jupyter_notebook/dataset/1007/venous phase/20022.dcm  
  inflat

  inflating: /root/jupyter_notebook/dataset/1008/venous phase/20025.dcm  
  inflating: /root/jupyter_notebook/dataset/1008/venous phase/20025_mask.png  
  inflating: /root/jupyter_notebook/dataset/1008/venous phase/20026.dcm  
  inflating: /root/jupyter_notebook/dataset/1008/venous phase/20026_mask.png  
  inflating: /root/jupyter_notebook/dataset/1008/venous phase/20027.dcm  
  inflating: /root/jupyter_notebook/dataset/1008/venous phase/20027_mask.png  
  inflating: /root/jupyter_notebook/dataset/1008/venous phase/20028.dcm  
  inflating: /root/jupyter_notebook/dataset/1008/venous phase/20028_mask.png  
  inflating: /root/jupyter_notebook/dataset/1008/venous phase/20029.dcm  
  inflating: /root/jupyter_notebook/dataset/1008/venous phase/20029_mask.png  
  inflating: /root/jupyter_notebook/dataset/1008/venous phase/20030.dcm  
  inflating: /root/jupyter_notebook/dataset/1008/venous phase/20030_mask.png  
  inflating: /root/jupyter_notebook/dataset/1008/venous phase/20031.dcm  
  inflat

  inflating: /root/jupyter_notebook/dataset/1009/venous phase/20020.dcm  
  inflating: /root/jupyter_notebook/dataset/1009/venous phase/20020_mask.png  
  inflating: /root/jupyter_notebook/dataset/1009/venous phase/20021.dcm  
  inflating: /root/jupyter_notebook/dataset/1009/venous phase/20021_mask.png  
  inflating: /root/jupyter_notebook/dataset/1009/venous phase/20022.dcm  
  inflating: /root/jupyter_notebook/dataset/1009/venous phase/20022_mask.png  
  inflating: /root/jupyter_notebook/dataset/1009/venous phase/20023.dcm  
  inflating: /root/jupyter_notebook/dataset/1009/venous phase/20023_mask.png  
  inflating: /root/jupyter_notebook/dataset/1009/venous phase/20024.dcm  
  inflating: /root/jupyter_notebook/dataset/1009/venous phase/20024_mask.png  
  inflating: /root/jupyter_notebook/dataset/1009/venous phase/20025.dcm  
  inflating: /root/jupyter_notebook/dataset/1009/venous phase/20025_mask.png  
  inflating: /root/jupyter_notebook/dataset/1009/venous phase/20026.dcm  
  inflat

In [2]:
import matplotlib.pyplot as plt
import numpy as np
import SimpleITK as sitk
import glob
import pandas as pd
import os
from sklearn.model_selection import train_test_split
from Features import *  

def cut_image(img_names,mask_names):
    mask=plt.imread(mask_names)
    img=sitk.ReadImage(img_names)
    img_array=sitk.GetArrayFromImage(img)[0]
    arrays = (mask * img_array)
    sums =np.sum(arrays,axis=1)
    for i in range(len(sums)):
        if sums[i]!=0:
            arrays=arrays[i-20:i+80,200:300]
            break
    return arrays.reshape(100,100,1)

def files():
    files = pd.read_csv('clinical_data.csv', sep=',', encoding='gbk')
    files = files.iloc[-10:]
    values = files.values
    cnndatas=[]
    featuredatas=[]
    labels=[]
    j=0
    for val in values:
        name = val[2]
        label = val[3]
        if val[0]=='m':
            sex=1
        else:
            sex=0
        age=int(val[1][:2])
        imgnames = glob.glob('./dataset/' + str(name) + '/' + 'arterial phase' + '/*.dcm')
        masknames = glob.glob('./dataset/' + str(name) + '/' + 'arterial phase' + '/*.png')
        for img, mask in zip(imgnames, masknames):
            array = plt.imread(mask)
            sums = np.sum(array)
            if sums != 0:
                featur, lens = features(mask, img)
                featur.append(sex)
                featur.append(age)
                cnndatas.append(cut_image(img, mask))
                featuredatas.append(featur)
                if label == '+':
                    labels.append(1)
                else:
                    labels.append(0)
                j += 1
                if j % 10 == 0:
                    print("数据加载：", j)
    cnndatas=np.array(cnndatas)
    print('cnndatas:',cnndatas)
    featuredatas=np.array(featuredatas)
    print('featuredatas:',featuredatas)
    labels=np.array(labels)
    print('labels:',labels)
    print("保存数据集")
    np.save('cnndata.npy', cnndatas)
    np.save('label.npy', labels)
    np.save('featuredata.npy', featuredatas)
    return  cnndatas,featuredatas,labels
cnndatas,featuredatas,labels = files()

数据加载： 10
数据加载： 20
数据加载： 30
数据加载： 40
数据加载： 50
数据加载： 60
数据加载： 70
cnndatas: [[[[-0.]
   [-0.]
   [-0.]
   ...
   [-0.]
   [-0.]
   [-0.]]

  [[-0.]
   [-0.]
   [-0.]
   ...
   [-0.]
   [-0.]
   [-0.]]

  [[-0.]
   [-0.]
   [-0.]
   ...
   [-0.]
   [-0.]
   [-0.]]

  ...

  [[-0.]
   [-0.]
   [-0.]
   ...
   [ 0.]
   [ 0.]
   [-0.]]

  [[-0.]
   [-0.]
   [-0.]
   ...
   [-0.]
   [-0.]
   [-0.]]

  [[-0.]
   [-0.]
   [-0.]
   ...
   [-0.]
   [-0.]
   [-0.]]]


 [[[ 0.]
   [-0.]
   [-0.]
   ...
   [ 0.]
   [-0.]
   [-0.]]

  [[ 0.]
   [ 0.]
   [-0.]
   ...
   [-0.]
   [-0.]
   [-0.]]

  [[ 0.]
   [-0.]
   [-0.]
   ...
   [-0.]
   [-0.]
   [-0.]]

  ...

  [[ 0.]
   [ 0.]
   [ 0.]
   ...
   [-0.]
   [-0.]
   [-0.]]

  [[ 0.]
   [ 0.]
   [ 0.]
   ...
   [-0.]
   [-0.]
   [-0.]]

  [[-0.]
   [-0.]
   [-0.]
   ...
   [ 0.]
   [ 0.]
   [ 0.]]]


 [[[-0.]
   [-0.]
   [-0.]
   ...
   [-0.]
   [-0.]
   [-0.]]

  [[-0.]
   [-0.]
   [-0.]
   ...
   [-0.]
   [-0.]
   [-0.]]

  [[-0.]
   [-0.]
   [-0.]


## 2 模型训练

In [4]:
import tensorflow as tf

cnndata=np.load('cnndata.npy',allow_pickle=True)
featuredata=np.load('featuredata.npy',allow_pickle=True)
label=np.load('label.npy',allow_pickle=True)

train_cnn, test_cnn, train_label, test_label = train_test_split(cnndata, label, test_size=0.2,random_state=1)

train_feature,test_feature,feature_train_label,feature_test_label=train_test_split(featuredata, label, test_size=0.2,random_state=1)

num_classes=len(set(train_label))


datas_placeholder = tf.placeholder(tf.float32, [None, 100,100,1])
labels_placeholder = tf.placeholder(tf.int32, [None])
dropout_placeholdr = tf.placeholder(tf.float32)
def average_pool():
    conv0 = tf.layers.conv2d(datas_placeholder, 20, 5, activation=tf.nn.relu)
    pool0 = tf.layers.average_pooling2d(conv0, [2, 2], [2, 2])
    conv1 = tf.layers.conv2d(pool0, 40, 4, activation=tf.nn.relu)
    pool1 = tf.layers.average_pooling2d(conv1,  [2, 2], [2, 2])
    conv2 = tf.layers.conv2d(pool1, 80, 2, activation=tf.nn.relu)
    pool2 = tf.layers.average_pooling2d(conv2,  [2, 2], [2, 2])
    return pool2

pool2=average_pool()
flatten = tf.layers.flatten(pool2)
fc = tf.layers.dense(flatten, 450 , activation=tf.nn.relu)
dropout_fc = tf.layers.dropout(fc, dropout_placeholdr)
logits = tf.layers.dense(fc,num_classes)
predicted_labels = tf.argmax(logits, 1)
losses = tf.nn.softmax_cross_entropy_with_logits(
    labels=tf.one_hot(labels_placeholder, num_classes),
    logits=logits)


mean_loss = tf.reduce_mean(losses)
optimizer = tf.train.AdamOptimizer(learning_rate=1e-2).minimize(losses)
saver = tf.train.Saver()
def run_trains(model_path):
    with tf.Session() as sess:
        print("训练模式")
        sess.run(tf.global_variables_initializer())
        batch_size=60
        input_count=len(train_cnn)
        batches_count=int(input_count/batch_size)
        remainder=input_count%batch_size
        print("数据集分成 %s 批, 前面每批 %s 个数据，最后一批 %s 个数据" % (batches_count + 1, batch_size, remainder))
        for step in range(60):
            for n in range(batches_count):
                train_feed_dict = {
                    datas_placeholder: train_cnn[n*batch_size:(n+1)*batch_size],
                    labels_placeholder: train_label[n*batch_size:(n+1)*batch_size],
                    dropout_placeholdr: 0.25,
                }
                _, mean_loss_val = sess.run([optimizer, mean_loss], feed_dict=train_feed_dict)
                print("n = {}%tmean loss = {}".format(n, mean_loss_val))
            if remainder>0:
                start_index = batches_count * batch_size
                train_feed_dict = {
                    datas_placeholder: train_cnn[start_index:input_count-1],
                    labels_placeholder: train_label[start_index:input_count-1],
                    dropout_placeholdr: 0.25,
                }
            _, mean_loss_val = sess.run([optimizer, mean_loss], feed_dict=train_feed_dict)
            print("step = {}%tmean loss = {}".format(step, mean_loss_val))
            print("保存模型")
            saver.save(sess, model_path)
            print("训练结束，保存模型到{}".format(model_path))
def run_tests(model_path):
    with tf.Session() as sess:
        print("测试模式")
        saver.restore(sess, model_path)
        print("从{}载入模型".format(model_path))
        test_feed_dict = {
            datas_placeholder: test_cnn,
            labels_placeholder: test_label,
            dropout_placeholdr: 0
        }
        predicted_labels_val = sess.run(predicted_labels, feed_dict=test_feed_dict)
        m=0
        j=0
        for real_label, predicted_label in zip(test_label, predicted_labels_val):
            if real_label==predicted_label:
                m+=1
            j+=1
        print("预测准确率：{}".format(float(m/j)))
    return predicted_labels_val
def get_features(model_path,x_data,y_data):
    with tf.Session() as sess:
        saver.restore(sess, model_path)
        test_feed_dict = {
            datas_placeholder: x_data,
            labels_placeholder: y_data,
            dropout_placeholdr: 0
        }
        predicted_labels_val = sess.run(fc, feed_dict=test_feed_dict)
    return predicted_labels_val

def train_feature(traindata,trainlabel,testdata,testlable,model_path,i):
    clf = RandomForestClassifier(n_estimators=i,max_depth=None,random_state=0)
    clf.fit(traindata,trainlabel)
    joblib.dump(clf,paths)

def make_randomforest(testdata,testlabel):
    clf = joblib.load(model_path)
    values = cf.predict(testdata)
    return values

run_trains('./dataset')

/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarnin

Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See @{tf.nn.softmax_cross_entropy_with_logits_v2}.

训练模式
数据集分成 1 批, 前面每批 60 个数据，最后一批 58 个数据
step = 0%tmean loss = 1.210063099861145
保存模型
训练结束，保存模型到./dataset
step = 1%tmean loss = 663.2288818359375
保存模型
训练结束，保存模型到./dataset
step = 2%tmean loss = 8.094110488891602
保存模型
训练结束，保存模型到./dataset
step = 3%tmean loss = 9.898920059204102
保存模型
训练结束，保存模型到./dataset
step = 4%tmean loss = 12.312524795532227
保存模型
训练结束，保存模型到./dataset
step = 5%tmean loss = 5.345033168792725
保存模型
训练结束，保存模型到./dataset
step = 6%tmean loss = 0.21119557321071625
保存模型
训练结束，保存模型到./dataset
step = 7%tmean loss = 1.4247567653656006
保存模型
训练结束，保存模型到./dataset
step = 8%tmean loss = 0.4167306125164032
保存模型
训练结束，保存模型到./dataset
step = 9%tmean loss = 3.23359751701355
保存模型
训练结束，保存模型到./dataset
step = 10%tmean loss = 0.14762648940086365
保存模型
训练结束，保存模型到./dataset
step = 11%tmean loss = 0.1518806517124176
保存模型

In [5]:
run_tests('./dataset')

测试模式
INFO:tensorflow:Restoring parameters from ./dataset
从./dataset载入模型
预测准确率：0.7333333333333333


array([1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0])